

services:
  user-ms:
    build:
      context: .
      dockerfile: services/user-ms/Dockerfile
    ports:
      - "8080:8080"
      - "50051:50051"
    env_file:
      - .env

  product-ms:
    build:
      context: .
      dockerfile: services/product-ms/Dockerfile
    ports:
      - "8081:8081"
      - "50052:50052"
    env_file:
      - .env
    depends_on:
      user-ms:
        condition: service_started

  cart-ms:
    build:
      context: .
      dockerfile: services/cart-ms/Dockerfile
    ports:
      - "8083:8083"
      - "50053:50053"
    env_file:
      - .env
    depends_on:
      user-ms:
        condition: service_started
      product-ms:
        condition: service_started

  order-ms:
    build:
      context: .
      dockerfile: services/order-ms/Dockerfile
    ports:
      - "8084:8084"
      - "50054:50054"
    env_file:
      - .env
    depends_on:
      user-ms:
        condition: service_started
      product-ms:
        condition: service_started
      cart-ms:
        condition: service_started

  payment-ms:
    build:
      context: .
      dockerfile: services/payment-ms/Dockerfile
    ports:
      - "8085:8085"
      - "50055:50055"
    env_file:
      - .env
    depends_on:
      order-ms:
        condition: service_started



  zookeeper:
    image: confluentinc/cp-zookeeper:7.0.1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.0.1
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
