FROM golang:1.25-alpine AS builder
WORKDIR /app

RUN apk add --no-cache git
ENV GOPROXY=https://proxy.golang.org,direct
ENV GOSUMDB=sum.golang.org

COPY go.work .
COPY pkg ./pkg
COPY services ./services

RUN go work sync

WORKDIR /app/services/payment-ms
RUN go build -o /app/payment-ms ./cmd

FROM alpine:latest
WORKDIR /app
COPY --from=builder /app/payment-ms .
EXPOSE 8085 50055
CMD ["./payment-ms"]
